# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'models/main_window.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1042, 753)
        MainWindow.setStyleSheet(_fromUtf8(".QButton#btnSettings{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(109, 140, 163, 255), stop:0.77665 rgba(74, 75, 59, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
".QGroupBox\n"
"{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:1, stop:0 rgba(151, 151, 151, 64), stop:1 rgba(255, 255, 255, 0));\n"
"font: bold;\n"
"}\n"
".QLabel#lbSettings\n"
"{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(40, 61, 139, 255), stop:1 rgba(60, 23, 120, 134));\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
".QTextEdit\n"
"{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(30, 26, 47, 255), stop:0.55 rgba(24, 42, 69, 255), stop:0.985 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));\n"
"background-image: url(:/img/appium_logo_rgb.png);\n"
"background-repeat: no-repeat;\n"
"background-position: right bottom;\n"
"background-attachment: fixed;\n"
"color: rgb(231, 231, 231);\n"
"}"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lbStatus = QtGui.QLabel(self.centralwidget)
        self.lbStatus.setObjectName(_fromUtf8("lbStatus"))
        self.gridLayout_2.addWidget(self.lbStatus, 2, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnAbout = QtGui.QPushButton(self.centralwidget)
        self.btnAbout.setObjectName(_fromUtf8("btnAbout"))
        self.horizontalLayout.addWidget(self.btnAbout)
        self.btnSettings = QtGui.QPushButton(self.centralwidget)
        self.btnSettings.setDefault(False)
        self.btnSettings.setFlat(False)
        self.btnSettings.setObjectName(_fromUtf8("btnSettings"))
        self.horizontalLayout.addWidget(self.btnSettings)
        self.btnCancel = QtGui.QPushButton(self.centralwidget)
        self.btnCancel.setObjectName(_fromUtf8("btnCancel"))
        self.horizontalLayout.addWidget(self.btnCancel)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnRun = QtGui.QPushButton(self.centralwidget)
        self.btnRun.setObjectName(_fromUtf8("btnRun"))
        self.horizontalLayout.addWidget(self.btnRun)
        self.btnClear = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnClear.sizePolicy().hasHeightForWidth())
        self.btnClear.setSizePolicy(sizePolicy)
        self.btnClear.setMinimumSize(QtCore.QSize(0, 0))
        self.btnClear.setObjectName(_fromUtf8("btnClear"))
        self.horizontalLayout.addWidget(self.btnClear)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.frmSettings = QtGui.QFrame(self.centralwidget)
        self.frmSettings.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmSettings.sizePolicy().hasHeightForWidth())
        self.frmSettings.setSizePolicy(sizePolicy)
        self.frmSettings.setMinimumSize(QtCore.QSize(0, 110))
        self.frmSettings.setObjectName(_fromUtf8("frmSettings"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frmSettings)
        self.gridLayout_3.setMargin(2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lbSettings = QtGui.QLabel(self.frmSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbSettings.sizePolicy().hasHeightForWidth())
        self.lbSettings.setSizePolicy(sizePolicy)
        self.lbSettings.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbSettings.setFont(font)
        self.lbSettings.setObjectName(_fromUtf8("lbSettings"))
        self.verticalLayout_2.addWidget(self.lbSettings)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.frame = QtGui.QFrame(self.frmSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 400))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.frame)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabMain = QtGui.QWidget()
        self.tabMain.setObjectName(_fromUtf8("tabMain"))
        self.gridLayoutWidget = QtGui.QWidget(self.tabMain)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 10, 259, 61))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lbAppPath = QtGui.QLabel(self.gridLayoutWidget)
        self.lbAppPath.setEnabled(False)
        self.lbAppPath.setObjectName(_fromUtf8("lbAppPath"))
        self.gridLayout_4.addWidget(self.lbAppPath, 0, 1, 1, 1)
        self.leAppPath = QtGui.QLineEdit(self.gridLayoutWidget)
        self.leAppPath.setEnabled(False)
        self.leAppPath.setObjectName(_fromUtf8("leAppPath"))
        self.gridLayout_4.addWidget(self.leAppPath, 1, 1, 1, 1)
        self.cbAppPath = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cbAppPath.setText(_fromUtf8(""))
        self.cbAppPath.setObjectName(_fromUtf8("cbAppPath"))
        self.gridLayout_4.addWidget(self.cbAppPath, 1, 0, 1, 1)
        self.btnAppPath = QtGui.QPushButton(self.gridLayoutWidget)
        self.btnAppPath.setEnabled(False)
        self.btnAppPath.setObjectName(_fromUtf8("btnAppPath"))
        self.gridLayout_4.addWidget(self.btnAppPath, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.tabMain)
        self.label_2.setGeometry(QtCore.QRect(860, 180, 57, 18))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lineEdit_3 = QtGui.QLineEdit(self.tabMain)
        self.lineEdit_3.setGeometry(QtCore.QRect(860, 210, 113, 30))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.comboBox = QtGui.QComboBox(self.tabMain)
        self.comboBox.setGeometry(QtCore.QRect(870, 140, 76, 26))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.checkBox = QtGui.QCheckBox(self.tabMain)
        self.checkBox.setGeometry(QtCore.QRect(870, 100, 86, 23))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.pushButton = QtGui.QPushButton(self.tabMain)
        self.pushButton.setGeometry(QtCore.QRect(870, 70, 87, 30))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.cbDontResetAppState = QtGui.QCheckBox(self.tabMain)
        self.cbDontResetAppState.setGeometry(QtCore.QRect(0, 300, 191, 23))
        self.cbDontResetAppState.setObjectName(_fromUtf8("cbDontResetAppState"))
        self.checkBox_2 = QtGui.QCheckBox(self.tabMain)
        self.checkBox_2.setGeometry(QtCore.QRect(830, 210, 19, 20))
        self.checkBox_2.setText(_fromUtf8(""))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.tabMain)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 80, 251, 61))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.cbAppPackage = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.cbAppPackage.setText(_fromUtf8(""))
        self.cbAppPackage.setObjectName(_fromUtf8("cbAppPackage"))
        self.gridLayout_5.addWidget(self.cbAppPackage, 1, 0, 1, 1)
        self.leAppPackage = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.leAppPackage.setEnabled(False)
        self.leAppPackage.setObjectName(_fromUtf8("leAppPackage"))
        self.gridLayout_5.addWidget(self.leAppPackage, 1, 1, 1, 1)
        self.lbAppPackage = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lbAppPackage.setEnabled(False)
        self.lbAppPackage.setObjectName(_fromUtf8("lbAppPackage"))
        self.gridLayout_5.addWidget(self.lbAppPackage, 0, 1, 1, 1)
        self.gridLayoutWidget_3 = QtGui.QWidget(self.tabMain)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 150, 251, 61))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_6 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.cbAppActivity = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.cbAppActivity.setText(_fromUtf8(""))
        self.cbAppActivity.setObjectName(_fromUtf8("cbAppActivity"))
        self.gridLayout_6.addWidget(self.cbAppActivity, 1, 0, 1, 1)
        self.leAppActivity = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.leAppActivity.setEnabled(False)
        self.leAppActivity.setObjectName(_fromUtf8("leAppActivity"))
        self.gridLayout_6.addWidget(self.leAppActivity, 1, 1, 1, 1)
        self.lbAppActivity = QtGui.QLabel(self.gridLayoutWidget_3)
        self.lbAppActivity.setEnabled(False)
        self.lbAppActivity.setObjectName(_fromUtf8("lbAppActivity"))
        self.gridLayout_6.addWidget(self.lbAppActivity, 0, 1, 1, 1)
        self.gridLayoutWidget_4 = QtGui.QWidget(self.tabMain)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(0, 220, 251, 61))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout_7 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.cbWaitForActivity = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.cbWaitForActivity.setText(_fromUtf8(""))
        self.cbWaitForActivity.setObjectName(_fromUtf8("cbWaitForActivity"))
        self.gridLayout_7.addWidget(self.cbWaitForActivity, 1, 0, 1, 1)
        self.leWaitForActivity = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.leWaitForActivity.setEnabled(False)
        self.leWaitForActivity.setObjectName(_fromUtf8("leWaitForActivity"))
        self.gridLayout_7.addWidget(self.leWaitForActivity, 1, 1, 1, 1)
        self.lbWaitForActivity = QtGui.QLabel(self.gridLayoutWidget_4)
        self.lbWaitForActivity.setEnabled(False)
        self.lbWaitForActivity.setObjectName(_fromUtf8("lbWaitForActivity"))
        self.gridLayout_7.addWidget(self.lbWaitForActivity, 0, 1, 1, 1)
        self.gridLayoutWidget_7 = QtGui.QWidget(self.tabMain)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(270, 80, 221, 61))
        self.gridLayoutWidget_7.setObjectName(_fromUtf8("gridLayoutWidget_7"))
        self.gridLayout_10 = QtGui.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.cbDeviceReadyTimeout = QtGui.QCheckBox(self.gridLayoutWidget_7)
        self.cbDeviceReadyTimeout.setText(_fromUtf8(""))
        self.cbDeviceReadyTimeout.setObjectName(_fromUtf8("cbDeviceReadyTimeout"))
        self.gridLayout_10.addWidget(self.cbDeviceReadyTimeout, 1, 0, 1, 1)
        self.lbDeviceReadyTimeout = QtGui.QLabel(self.gridLayoutWidget_7)
        self.lbDeviceReadyTimeout.setEnabled(False)
        self.lbDeviceReadyTimeout.setObjectName(_fromUtf8("lbDeviceReadyTimeout"))
        self.gridLayout_10.addWidget(self.lbDeviceReadyTimeout, 0, 1, 1, 1)
        self.sbDeviceReadyTimeout = QtGui.QSpinBox(self.gridLayoutWidget_7)
        self.sbDeviceReadyTimeout.setEnabled(False)
        self.sbDeviceReadyTimeout.setObjectName(_fromUtf8("sbDeviceReadyTimeout"))
        self.gridLayout_10.addWidget(self.sbDeviceReadyTimeout, 1, 1, 1, 1)
        self.gridLayoutWidget_8 = QtGui.QWidget(self.tabMain)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(270, 10, 251, 61))
        self.gridLayoutWidget_8.setObjectName(_fromUtf8("gridLayoutWidget_8"))
        self.gridLayout_11 = QtGui.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.cbDeviceName = QtGui.QCheckBox(self.gridLayoutWidget_8)
        self.cbDeviceName.setText(_fromUtf8(""))
        self.cbDeviceName.setObjectName(_fromUtf8("cbDeviceName"))
        self.gridLayout_11.addWidget(self.cbDeviceName, 1, 0, 1, 1)
        self.leDeviceName = QtGui.QLineEdit(self.gridLayoutWidget_8)
        self.leDeviceName.setEnabled(False)
        self.leDeviceName.setObjectName(_fromUtf8("leDeviceName"))
        self.gridLayout_11.addWidget(self.leDeviceName, 1, 1, 1, 1)
        self.lbDeviceName = QtGui.QLabel(self.gridLayoutWidget_8)
        self.lbDeviceName.setEnabled(False)
        self.lbDeviceName.setObjectName(_fromUtf8("lbDeviceName"))
        self.gridLayout_11.addWidget(self.lbDeviceName, 0, 1, 1, 1)
        self.spinBox = QtGui.QSpinBox(self.tabMain)
        self.spinBox.setGeometry(QtCore.QRect(900, 250, 48, 28))
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.tabWidget.addTab(self.tabMain, _fromUtf8(""))
        self.tabLog = QtGui.QWidget()
        self.tabLog.setObjectName(_fromUtf8("tabLog"))
        self.layoutWidget_2 = QtGui.QWidget(self.tabLog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 120, 165, 28))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lbOutputMode = QtGui.QLabel(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbOutputMode.sizePolicy().hasHeightForWidth())
        self.lbOutputMode.setSizePolicy(sizePolicy)
        self.lbOutputMode.setMinimumSize(QtCore.QSize(0, 24))
        self.lbOutputMode.setObjectName(_fromUtf8("lbOutputMode"))
        self.horizontalLayout_4.addWidget(self.lbOutputMode)
        self.cmbOutputMode = QtGui.QComboBox(self.layoutWidget_2)
        self.cmbOutputMode.setMinimumSize(QtCore.QSize(0, 24))
        self.cmbOutputMode.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.cmbOutputMode.setObjectName(_fromUtf8("cmbOutputMode"))
        self.horizontalLayout_4.addWidget(self.cmbOutputMode)
        self.cbColorOutput = QtGui.QCheckBox(self.tabLog)
        self.cbColorOutput.setGeometry(QtCore.QRect(20, 30, 125, 23))
        self.cbColorOutput.setAutoFillBackground(False)
        self.cbColorOutput.setObjectName(_fromUtf8("cbColorOutput"))
        self.line = QtGui.QFrame(self.tabLog)
        self.line.setGeometry(QtCore.QRect(203, 10, 20, 271))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.layoutWidget = QtGui.QWidget(self.tabLog)
        self.layoutWidget.setGeometry(QtCore.QRect(220, 25, 221, 61))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.cbLogOutput = QtGui.QCheckBox(self.layoutWidget)
        self.cbLogOutput.setObjectName(_fromUtf8("cbLogOutput"))
        self.horizontalLayout_5.addWidget(self.cbLogOutput)
        self.btnLogOutputBrowse = QtGui.QPushButton(self.layoutWidget)
        self.btnLogOutputBrowse.setObjectName(_fromUtf8("btnLogOutputBrowse"))
        self.horizontalLayout_5.addWidget(self.btnLogOutputBrowse)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.lbLogOutputFileName = QtGui.QLabel(self.layoutWidget)
        self.lbLogOutputFileName.setObjectName(_fromUtf8("lbLogOutputFileName"))
        self.verticalLayout_4.addWidget(self.lbLogOutputFileName)
        self.layoutWidget1 = QtGui.QWidget(self.tabLog)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 60, 166, 56))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.cbShowTimeStamp = QtGui.QCheckBox(self.layoutWidget1)
        self.cbShowTimeStamp.setAutoFillBackground(False)
        self.cbShowTimeStamp.setObjectName(_fromUtf8("cbShowTimeStamp"))
        self.verticalLayout_5.addWidget(self.cbShowTimeStamp)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem1 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.cbUseLocalTimeZone = QtGui.QCheckBox(self.layoutWidget1)
        self.cbUseLocalTimeZone.setEnabled(False)
        self.cbUseLocalTimeZone.setObjectName(_fromUtf8("cbUseLocalTimeZone"))
        self.horizontalLayout_6.addWidget(self.cbUseLocalTimeZone)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.tabWidget.addTab(self.tabLog, _fromUtf8(""))
        self.tabAppium = QtGui.QWidget()
        self.tabAppium.setObjectName(_fromUtf8("tabAppium"))
        self.layoutWidget_3 = QtGui.QWidget(self.tabAppium)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 10, 301, 61))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.lbAppiumLocation = QtGui.QLabel(self.layoutWidget_3)
        self.lbAppiumLocation.setObjectName(_fromUtf8("lbAppiumLocation"))
        self.verticalLayout_3.addWidget(self.lbAppiumLocation)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.leAppiumLocation = QtGui.QLineEdit(self.layoutWidget_3)
        self.leAppiumLocation.setMinimumSize(QtCore.QSize(0, 26))
        self.leAppiumLocation.setObjectName(_fromUtf8("leAppiumLocation"))
        self.horizontalLayout_3.addWidget(self.leAppiumLocation)
        self.btnBrowseAppiumLocation = QtGui.QPushButton(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBrowseAppiumLocation.sizePolicy().hasHeightForWidth())
        self.btnBrowseAppiumLocation.setSizePolicy(sizePolicy)
        self.btnBrowseAppiumLocation.setMinimumSize(QtCore.QSize(0, 26))
        self.btnBrowseAppiumLocation.setObjectName(_fromUtf8("btnBrowseAppiumLocation"))
        self.horizontalLayout_3.addWidget(self.btnBrowseAppiumLocation)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.cbShowStartupCmd = QtGui.QCheckBox(self.tabAppium)
        self.cbShowStartupCmd.setGeometry(QtCore.QRect(10, 80, 165, 23))
        self.cbShowStartupCmd.setObjectName(_fromUtf8("cbShowStartupCmd"))
        self.layoutWidget_4 = QtGui.QWidget(self.tabAppium)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 110, 260, 61))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_7.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.lbServerAddress = QtGui.QLabel(self.layoutWidget_4)
        self.lbServerAddress.setEnabled(False)
        self.lbServerAddress.setObjectName(_fromUtf8("lbServerAddress"))
        self.gridLayout_8.addWidget(self.lbServerAddress, 0, 1, 1, 1)
        self.leServerAddress = QtGui.QLineEdit(self.layoutWidget_4)
        self.leServerAddress.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leServerAddress.sizePolicy().hasHeightForWidth())
        self.leServerAddress.setSizePolicy(sizePolicy)
        self.leServerAddress.setMinimumSize(QtCore.QSize(138, 0))
        self.leServerAddress.setObjectName(_fromUtf8("leServerAddress"))
        self.gridLayout_8.addWidget(self.leServerAddress, 1, 1, 1, 1)
        self.cbServerAddress = QtGui.QCheckBox(self.layoutWidget_4)
        self.cbServerAddress.setText(_fromUtf8(""))
        self.cbServerAddress.setObjectName(_fromUtf8("cbServerAddress"))
        self.gridLayout_8.addWidget(self.cbServerAddress, 1, 0, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout_8)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.leServerPort = QtGui.QLineEdit(self.layoutWidget_4)
        self.leServerPort.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leServerPort.sizePolicy().hasHeightForWidth())
        self.leServerPort.setSizePolicy(sizePolicy)
        self.leServerPort.setMinimumSize(QtCore.QSize(60, 0))
        self.leServerPort.setObjectName(_fromUtf8("leServerPort"))
        self.gridLayout_9.addWidget(self.leServerPort, 1, 1, 1, 1)
        self.lbServerPort = QtGui.QLabel(self.layoutWidget_4)
        self.lbServerPort.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbServerPort.sizePolicy().hasHeightForWidth())
        self.lbServerPort.setSizePolicy(sizePolicy)
        self.lbServerPort.setObjectName(_fromUtf8("lbServerPort"))
        self.gridLayout_9.addWidget(self.lbServerPort, 0, 1, 1, 1)
        self.cbServerPort = QtGui.QCheckBox(self.layoutWidget_4)
        self.cbServerPort.setText(_fromUtf8(""))
        self.cbServerPort.setObjectName(_fromUtf8("cbServerPort"))
        self.gridLayout_9.addWidget(self.cbServerPort, 1, 0, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout_9)
        self.gridLayoutWidget_9 = QtGui.QWidget(self.tabAppium)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(10, 180, 195, 59))
        self.gridLayoutWidget_9.setObjectName(_fromUtf8("gridLayoutWidget_9"))
        self.gridLayout_12 = QtGui.QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.lbServerCommandTimeout = QtGui.QLabel(self.gridLayoutWidget_9)
        self.lbServerCommandTimeout.setEnabled(False)
        self.lbServerCommandTimeout.setObjectName(_fromUtf8("lbServerCommandTimeout"))
        self.gridLayout_12.addWidget(self.lbServerCommandTimeout, 0, 1, 1, 1)
        self.cbServerCommandTimeout = QtGui.QCheckBox(self.gridLayoutWidget_9)
        self.cbServerCommandTimeout.setText(_fromUtf8(""))
        self.cbServerCommandTimeout.setObjectName(_fromUtf8("cbServerCommandTimeout"))
        self.gridLayout_12.addWidget(self.cbServerCommandTimeout, 1, 0, 1, 1)
        self.sbServerCommandTimeout = QtGui.QSpinBox(self.gridLayoutWidget_9)
        self.sbServerCommandTimeout.setEnabled(False)
        self.sbServerCommandTimeout.setObjectName(_fromUtf8("sbServerCommandTimeout"))
        self.gridLayout_12.addWidget(self.sbServerCommandTimeout, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tabAppium, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frmSettings)
        self.teOutput = QtGui.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(12)
        self.teOutput.setFont(font)
        self.teOutput.setReadOnly(True)
        self.teOutput.setHtml(_fromUtf8("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Monospace\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.teOutput.setAcceptRichText(True)
        self.teOutput.setObjectName(_fromUtf8("teOutput"))
        self.verticalLayout.addWidget(self.teOutput)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Appium Runner", None))
        self.lbStatus.setText(_translate("MainWindow", "Idle.", None))
        self.btnAbout.setText(_translate("MainWindow", "About", None))
        self.btnSettings.setText(_translate("MainWindow", "Settings", None))
        self.btnCancel.setText(_translate("MainWindow", "Cancel", None))
        self.btnRun.setText(_translate("MainWindow", "Run", None))
        self.btnClear.setText(_translate("MainWindow", "Clear", None))
        self.lbSettings.setText(_translate("MainWindow", " Appium Settings", None))
        self.lbAppPath.setText(_translate("MainWindow", "Application path (*.apk):", None))
        self.btnAppPath.setText(_translate("MainWindow", "Browse", None))
        self.label_2.setText(_translate("MainWindow", "TextLabel", None))
        self.checkBox.setText(_translate("MainWindow", "CheckBox", None))
        self.pushButton.setText(_translate("MainWindow", "PushButton", None))
        self.cbDontResetAppState.setText(_translate("MainWindow", "Don\'t reset application state", None))
        self.lbAppPackage.setText(_translate("MainWindow", "Package (e.g. .com.app.packageName):", None))
        self.lbAppActivity.setText(_translate("MainWindow", "Activity (e.g. MainActivity):", None))
        self.lbWaitForActivity.setText(_translate("MainWindow", "Wait for activity (e.g. MainActivity):", None))
        self.lbDeviceReadyTimeout.setText(_translate("MainWindow", "Device READY timeout (seconds):", None))
        self.lbDeviceName.setText(_translate("MainWindow", "Device name:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMain), _translate("MainWindow", "Main", None))
        self.lbOutputMode.setText(_translate("MainWindow", "Output Mode:", None))
        self.cbColorOutput.setText(_translate("MainWindow", "Color output", None))
        self.cbLogOutput.setText(_translate("MainWindow", "Log to file", None))
        self.btnLogOutputBrowse.setText(_translate("MainWindow", "Browse", None))
        self.lbLogOutputFileName.setText(_translate("MainWindow", "(none)", None))
        self.cbShowTimeStamp.setText(_translate("MainWindow", "Show timestamp", None))
        self.cbUseLocalTimeZone.setText(_translate("MainWindow", "Use local time zone", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLog), _translate("MainWindow", "Output / Log", None))
        self.lbAppiumLocation.setText(_translate("MainWindow", "Appium Location:", None))
        self.btnBrowseAppiumLocation.setText(_translate("MainWindow", "Browse", None))
        self.cbShowStartupCmd.setText(_translate("MainWindow", "Show startup command", None))
        self.lbServerAddress.setText(_translate("MainWindow", "Address:", None))
        self.lbServerPort.setText(_translate("MainWindow", "Port:", None))
        self.lbServerCommandTimeout.setText(_translate("MainWindow", "Command timeout (seconds):", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAppium), _translate("MainWindow", "Appium", None))

import resources_rc
